---
title: "Recombination Probabilities"
author:
- Douglas A. Campbell
- Natasha Ryan
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
    code_folding: hide
    keep_md: yes
    fig_caption: yes
    toc: TRUE
    toc_float: TRUE   
csl: plos-one.csl
editor_options: 
  chunk_output_type: inline
---



```{r load libraries}

library(tidyverse)
library(readxl)
library(stringr)
library(broom)
library(minpack.lm)
#library(OneR)
library(changepoint)
library(chngpt)
library(broom)
library(Rwave)
library(WaveletComp)

```

# Set Project Variables
```{r set project variables}
Project <- "LOW"
DataIn <- file.path("..","Data", "CleanData")
CalibData <- file.path("..","Data", "CalibData")
FileID <- "SolFitsTrim2"

```


```{r start variables}
PSIIo <- 1000 #PSII)
sigmaPSII <- 250e-20 #m2 photon-1
FlashletEx <- 30000 #umol photons m-2 s-1
Flashlet_s <- 1.2e-6
FlashTrain <- 40
Dark_s <- 2e-6
Photons_umol <- 6.33E17

SNL <- 0.01
Recomb <- 0.05

qp <- 0.95
ExcitPSIIPhotons = FlashletEx * Photons_umol * sigmaPSII * FlashTrain * Flashlet_s

ExcitPSIIPhotons

tau_s = 1e-3

PSIIreopen = PSIIo - (PSIIo * exp(-1/tau_s  * FlashTrain * (Flashlet_s + Dark_s)))

PSIIreopen
```

```{r import clean data}

FitFilesSol <- list.files(path = DataIn, pattern = FileID, full.names = TRUE)

read.RDS <- function(flnm){readRDS(flnm) |>
    mutate(filename = flnm)
}

#test for duplicate file names
unique(duplicated(FitFilesSol))

LOW_SolFits <- FitFilesSol |>
  purrr::map_df(~read.RDS(flnm = .))


```

```{r dummy data}
DummyData <- tibble(FlashTrain = c(1:12), FM = c(63, 56, 56, 60, 59, 57, 58, 59, 58, 57, 58, 58))

DummyData |>
  ggplot() +
  geom_line(aes(x = FlashTrain, y = FM)) +
  theme_bw()
```


Measure fraction of PSII closed after a flashtrain; that gives fraction of PSII that 'miss' advancing
Use Poisson distribution to estimate probability of double turnover during tau
Check on simulataneous rates arithmetic

```{r simulation}
Simulate <- tibble(Flash = c(0:59),
                   SState = rep(c(1:4),times = 15),
                   PSIIclose = PSIIo * qp^Flash,
                   PSIIreopen = PSIIclose - (PSIIclose * exp(-1/tau_s  * FlashTrain * (Flashlet_s + Dark_s))),
                   PSIInet = PSIIclose - PSIIreopen) |>
  mutate(YSPSII = case_when(SState == 1 ~ 1,
                           SState == 2 ~ 0.9,
                           SState == 3 ~ 0.9,
                           SState == 4 ~ 1)) |>
  mutate(meanYSPSII = mean(YSPSII)) |>
  mutate(FM = ((PSIInet * YSPSII) + ((PSIIo - PSIInet) * meanYSPSII))/PSIIo) |>
  mutate(YSPSIIupper = meanYSPSII + (meanYSPSII * SNL),
         YSPSIIlower = meanYSPSII - (meanYSPSII * SNL)) |>
  mutate(SignifFlash = if_else(FM <= YSPSIIupper & FM >= YSPSIIlower, 0, 1))

```


```{r simulate plot}
Simulate |>
  ggplot() +
  geom_point(aes(x = Flash, y = PSIInet/PSIIo)) +
  geom_point(aes(x = Flash, y = FM, colour = as.factor(SignifFlash))) +
  geom_line(aes(x = Flash, y = YSPSIIupper), linetype = "dashed", colour = "green") +
  geom_line(aes(x = Flash, y = YSPSIIlower), linetype = "dashed", colour = "green") +
  theme_bw()
```


```{r simulation with noise}
Simulate <- Simulate |>
  mutate(PSIInetnoise = PSIInet * (1 + rnorm(n=10, sd=SNL))) |>
  mutate(FMnoise = ((PSIInetnoise * YSPSII) + ((PSIIo - PSIInetnoise) * meanYSPSII))/PSIIo) |> 
  mutate(SignifFlashnoise = if_else(FMnoise <= YSPSIIupper & FM >= YSPSIIlower, 0, 1)) |>
  mutate(FlashThreshold =  as.numeric(filter(Simulate, SignifFlashnoise == 1) |>
  slice_tail(n = 1) |>
   select(Flash))
  )
  

Simulate |> 
  ggplot() +
  geom_point(aes(x = Flash, y = PSIInetnoise/PSIIo)) +
  geom_point(aes(x = Flash, y = FMnoise, colour = as.factor(SignifFlashnoise))) +
  geom_line(aes(x = Flash, y = YSPSIIupper), linetype = "dashed", colour = "green") +
  geom_line(aes(x = Flash, y = YSPSIIlower), linetype = "dashed", colour = "green") +
  geom_vline(xintercept = Simulate$FlashThreshold[1], linetype = "dashed", colour = "green") +
  geom_text(aes(x = FlashThreshold[1] + 1, y = 0.5, label = paste("Significance Threshold", FlashThreshold[1]))) +
  theme_bw()
```
```{r simulate with recombination}
Simulate <- Simulate |>
  mutate(PSIIreopenrecomb = PSIIreopen - (PSIIreopen * Recomb), .after = PSIIreopen) |>
  mutate(PSIInetrecomb = PSIInet - PSIIreopenrecomb, .after = PSIInet) |>
  mutate(PSIInetrecombnoise = PSIInetrecomb * (1 + rnorm(n=10, sd=SNL))) |>
  mutate(FMrecombnoise = ((PSIInetrecombnoise * YSPSII) + ((PSIIo - PSIInetrecombnoise) * meanYSPSII))/PSIIo) |>
  mutate(SignifFlashrecombnoise = if_else(FMrecombnoise <= YSPSIIupper & FMrecombnoise >= YSPSIIlower, 0, 1)) |>
  mutate(FlashrecombnoiseThreshold =  as.numeric(filter(Simulate, SignifFlashrecombnoise == 1) |>
  slice_tail(n = 1) |>
   select(Flash))
  )

#Issue with PSIIo does not take into account re-closure of PSIIo upon subsequent flashes




  
  Simulate |> 
  ggplot() +
    #geom_point(aes(x = Flash, y = PSIInetnoise/PSIIo)) + 
    geom_point(aes(x = Flash, y = PSIInetrecombnoise/PSIIo), colour = "red") +
    #geom_point(aes(x = Flash, y = FMnoise, colour = as.factor(SignifFlashnoise))) +
    geom_point(aes(x = Flash, y = FMrecombnoise, colour = as.factor(SignifFlashrecombnoise))) +
    geom_line(aes(x = Flash, y = YSPSIIupper), linetype = "dashed", colour = "green") +
    geom_line(aes(x = Flash, y = YSPSIIlower), linetype = "dashed", colour = "green") +
    geom_vline(xintercept = Simulate$FlashrecombnoiseThreshold[1], linetype = "dashed", colour = "red") +
    geom_text(aes(x = FlashrecombnoiseThreshold[1] + 1, y = 0.5, label = paste("Significance Threshold with Recombination", FlashrecombnoiseThreshold[1]))) +
    geom_vline(xintercept = Simulate$FlashThreshold[1], linetype = "dashed", colour = "darkgreen") +
  geom_text(aes(x = FlashThreshold[1] + 1, y = 0.6, label = paste("Significance Threshold", FlashThreshold[1]))) +
  theme_bw()
```

