---
title: "ChlamyANOVA"
author:
- Natasha Ryan
- Douglas A. Campbell
date: "`r format(Sys.Date())`"
output:
  html_document:
    df_print: paged
    code_folding: hide
    keep_md: yes
    fig_caption: yes
    toc: TRUE
    toc_float: TRUE   
csl: plos-one.csl
editor_options: 
  chunk_output_type: inline
---

*Some of the code used to create this R Notebook was refurbished from "PlateAbImport.Rmd" written by Maximilian Berthold, Douglas A. Campbell, Melissa L. Rioux, Sarah J Gore, and Alyson MacCormack.*

```{r load libraries}
library(tidyverse)
library(lubridate)
library(googlesheets4)
library(googledrive)
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_chunk$set(fig.path='Output/')
```

#Setup

### Set Project Variables 
```{r set project variables}
Project <- "LOW"
TargetData <- "Ottawa_2025"
DataIn <- file.path("..","Data", "ProcessedData")
CalibData <- file.path("..","Data", "CalibData")
DataOut <- file.path("..","Data", "ProcessedData")

FileID <- "fit"

FileEncode <- "UTF-8" #guess_encoding says 'ASCII"

Delimiter <- ","

HeaderRows <- 0

#conversions
# us_s = 1000000
photons_umol = 6.022E17
A2_m2 = 1E20


#set colours
TempColours = c("black","violet",  "blue", "darkgreen", "green", "orange", "red", "darkred")

names(TempColours) <- c(2, 4, 8, 12, 16, 20, 24, 28)

TempColours
```


```{r read Chlamy_damping}
Chlamy_damping <- readRDS(file.path(DataIn, "LOW_Chlamy_damping.Rds", fsep = .Platform$file.sep)) 

```



```{r test plots single flash space}

PulseSpaceSet = 2

Chlamy_damping |>
  filter(Strain == "Chlamydomonas_ICEMDV") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  ggplot() +
  geom_point(aes(x = PulseSpace_s, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(Temp_C), cols = vars(Strain, PulseSpace_s, NaCl_mM, Year)) +
  theme_bw()

SolFitsChlamyMeta |>
  filter(Strain == "Chlamydomonas_priscuii") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  ggplot() +
  geom_point(aes(x = Flashnumber, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(TempDiff_C, Temp_C), cols = vars(Strain, PulseSpace_s, NaCl_mM, Year)) +
  theme_bw()

SolFitsChlamyMeta |>
  filter(Strain == "Chlamydomonas_klinobasis") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  ggplot() +
  geom_line(aes(x = Flashnumber, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(TempDiff_C, Temp_C), cols = vars(Strain, PulseSpace_s, NaCl_mM, Year)) +
  theme_bw()

SolFitsChlamyMeta |>
  filter(Strain == "Chlamydomonas_malina") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  ggplot() +
  geom_point(aes(x = Flashnumber, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(TempDiff_C, Temp_C), cols = vars(Strain, PulseSpace_s, NaCl_mM, Year)) +
  theme_bw()

SolFitsChlamyMeta |>
  filter(Strain == "Chlamydomonas_euryale") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  ggplot() +
  geom_point(aes(x = Flashnumber, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(TempDiff_C, Temp_C), cols = vars(Strain, PulseSpace_s,NaCl_mM, Year)) +
  theme_bw()

SolFitsChlamyMeta |>
  filter(Strain == "Chlamydomonas_reinhardtii") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  ggplot() +
  geom_point(aes(x = Flashnumber, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(TempDiff_C, Temp_C), cols = vars(Strain, PulseSpace_s, NaCl_mM, Year)) +
  theme_bw()
```


```{r test plots single flash space SalOpt}

PulseSpaceSet = 2

SolFitsChlamyMeta |>
  filter(Strain == "Chlamydomonas_ICEMDV") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  filter(NaCl_mM == SalOpt) |>
  ggplot() +
  geom_point(aes(x = Flashnumber, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(TempDiff_C, Temp_C), cols = vars(Strain, PulseSpace_s, NaCl_mM)) +
  theme_bw()

 SolFitsChlamyMeta |>
  filter(Strain == "Chlamydomonas_priscuii") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  filter(NaCl_mM == SalOpt) |>
  ggplot() +
  geom_point(aes(x = Flashnumber, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(TempDiff_C, Temp_C), cols = vars(Strain, PulseSpace_s, NaCl_mM)) +
  theme_bw()

SolFitsChlamyMeta |>
  filter(Strain == "Chlamydomonas_klinobasis") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  filter(NaCl_mM == SalOpt) |>
  ggplot() +
  geom_line(aes(x = Flashnumber, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(TempDiff_C, Temp_C), cols = vars(Strain, PulseSpace_s, NaCl_mM)) +
  theme_bw()

SolFitsChlamyMeta |>
  filter(Strain == "Chlamydomonas_malina") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  filter(NaCl_mM == SalOpt) |>
  ggplot() +
  geom_point(aes(x = Flashnumber, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(TempDiff_C, Temp_C), cols = vars(Strain, PulseSpace_s, NaCl_mM)) +
  theme_bw()

SolFitsChlamyMeta |>
  filter(Strain == "Chlamydomonas_euryale") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  filter(NaCl_mM == SalOpt) |>
  ggplot() +
  geom_point(aes(x = Flashnumber, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(TempDiff_C, Temp_C), cols = vars(Strain, PulseSpace_s,NaCl_mM)) +
  theme_bw()

SolFitsChlamyMeta |>
  filter(Strain == "Chlamydomonas_reinhardtii") |>
  filter(PulseSpace_s == PulseSpaceSet) |>
  filter(NaCl_mM == SalOpt) |>
  ggplot() +
  geom_point(aes(x = Flashnumber, y = FvFmrunnorm, colour = as.factor(NaCl_mM))) +
  facet_grid(rows = vars(TempDiff_C, Temp_C), cols = vars(Strain, PulseSpace_s, NaCl_mM)) +
  theme_bw()
```
