---
title: "Thesis Figures"
author: "Natasha Ryan"
output: 
  html_document: default
  word_document: default
editor_options: 
  chunk_output_type: inline
---

This RMD imports data to generate figures for Natasha Ryan's undergraduate honours thesis at Mount Allison University. 


# Setup
```{r load libraries}
library(tidyverse)
library(metR)
library(viridis)
library(ggpubr)
```

```{r create ggplot theme}
theme_thesis <- function() {
  theme_bw() +
  theme(text = element_text(family = "Times New Roman"), 
        axis.text=element_text(size=11), axis.title=element_text(size=13),
        legend.text=element_text(size=11), legend.title=element_text(size=13),
        strip.background = element_rect(colour="black", fill=NA),
        strip.text = element_text(size=11), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()
  )
}

s.col <- c("#003D4F","#375D97","#3397A6","#9FD4C2")
```


# Methods 

```{r }
Fc_data <- readRDS("../Data/CleanData/LOW_Fragilariopsis_cylindrus_SolFitsTrim.Rds") %>%
  mutate(SState = ifelse(SState == 4, 0, SState))


# Fc_data %>%
#   filter(Filename == "20230926_SeGu1001_0C_1s") %>%
#   filter(Flashnumber <= 13) %>%
#   ggplot() +
#   geom_point(aes(x=Flashnumber, y=FvFmrunnorm, col=as.factor(SState))) +
#   scale_color_manual(values = s.col) +
#   #scale_y_continuous(limits=c(0.5, 1.1)) +
#   scale_x_continuous(breaks=c(4,8,12))+
#   labs(x= "Flash Number", y= "Normalized Chlorophyll Fluorescence") +
#   theme_bw() +
#   theme(legend.position = "none", text = element_text(family = "Palatino"),
#         axis.text=element_text(size=16), axis.title=element_text(size=14.8),
#         panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```



# Representative Fluorescence Oscillations

```{r warning=FALSE}
Cp_data <- readRDS("../Data/CleanData/LOW_Chlamydomonas_priscuii_SolFitsTrim.Rds") %>%
  mutate(SState = ifelse(SState == 4, 0, SState)) %>%
  ungroup()

Cp_data <- Cp_data %>%
    group_by(PulseSpace_s) %>%
    mutate(Approx_Light_Level = mean(as.numeric(Light_Level))) %>%
    mutate(Approx_Light_Level = round(Approx_Light_Level, 3)) %>%
    ungroup()
```


```{r warning=FALSE}
Cp_data %>%
  filter(Filename %in% c("20230918_MaPo1001_12C_1s", "20230918_MaPo1001_12C_4s", "20230919_MaPo1004_12C_16s",
                      "20230918_MaPo1001_4C_1s",  "20230918_MaPo1001_4C_4s", "20230918_MaPo1001_4C_16s")) %>%
  ggplot() +
  geom_point(aes(x=Flashnumber, y=FvFmrunnorm, col=as.factor(SState))) +
  scale_color_manual(values = s.col) +
  labs(x= "Flash Number", 
       y=expression("Normalized Chlorophyll Fluorescence (F"[v]*" / F"[m]*")"),
       col= "Majority S-State") +
  ggh4x::facet_nested(rows=vars(PulseSpace_s, Approx_Light_Level), cols=vars(Temp_C)) +
  scale_y_continuous(sec.axis=sec_axis(~ . , 
                     name = bquote(Steady ~ State ~ Light ~ (µmol ~ photons ~ m^-2 ~ s^-1)), 
                     breaks = NULL,labels = NULL)) +
  scale_x_continuous(breaks=c(4,8,12,16,20,24,28,32),
                     sec.axis=sec_axis(~ . , 
                                       name = sym("Measurement Temperature (°C)"), 
                                       breaks = NULL, labels = NULL)) +
  theme_thesis()

# ggsave("representativeoscillations.png", width = 9, height = 6, dpi = 900,
#       plot=last_plot(),
#       path="../Output")
```



# FFT
```{r}
Cp_data %>%
  filter(CultureID == "MaPo1001", 
         ObsDate == "2023-09-18", 
         Temp_C == 4, 
         PulseSpace_s == 1) %>%
  ggplot() +
  geom_point(aes(x=Flashnumber, y=FvFmrunnorm, col=as.factor(SState))) +
  scale_color_manual(values = s.col) +
  labs(x= "Flash Number", 
       y=expression("Normalized Chlorophyll Fluorescence (F"[v]*" / F"[m]*")"),
       col= "Majority S-State") +
  scale_x_continuous(breaks=c(4,8,12,16,20,24,28,32)) +
  theme_thesis() +
  theme(legend.position = "none")


# ggsave("wavelet_before.png", width = 4, height = 4, dpi = 900,
#        plot=last_plot(),
#        path="../Output")
```

```{r}
wave_data <- Cp_wavelets[["Cp_1_4_0.77084"]]


WaveletComp::reconstruct(wave_data, only.sig=FALSE,
            plot.waves = TRUE, plot.rec = FALSE,
            spec.time.axis = list(at = c(0,4,8,12,16,20,24,28,32)),
            timelab = "Flash Number",
            verbose = FALSE)
```


# Wavelet Periodicity 

```{r}
wavelets <- readRDS("../Data/ProcessedData/LOW_Wavelets.Rds") 
specieslists <- split(wavelets, sub("_.*", "_wavelets", names(wavelets)))
list2env(specieslists, envir = .GlobalEnv)

FcG0_wavelets <- Fc_wavelets[grepl(paste("_0$", collapse = "|"), names(Fc_wavelets))]
FcG6_wavelets <- Fc_wavelets[grepl(paste("_6$", collapse = "|"), names(Fc_wavelets))]
```

```{r periodicity function}
plot.wt.grid <- function(wavelets) {
  result_list <- lapply(names(wavelets), function(condition_name) {
    condition <- wavelets[[condition_name]]
    Power.avg <- condition$Power.avg
    Power.avg.pval <- condition$Power.avg.pval
    Period <- condition$Period
    Condition <- rep(condition_name, length(Power.avg))  # Repeat condition name for each row
    df <- data.frame(Power.avg, Power.avg.pval, Period, Condition) %>%
      separate(Condition, into = c("Strain", "PulseSpace_s", "Temp_C", "LightLevel"), sep = "_") %>%
      mutate(PulseSpace_s = factor(PulseSpace_s, levels = c("1", "2","4","8","16")),
             Temp_C = factor(Temp_C, levels = 
                           c("0","2","4","6","8","10","12","14","16","18","20","22","24","26","28"))) %>%
      mutate(Power.avg.pval = ifelse(Power.avg.pval <= 0.05, 0, 1))  %>%
    
     return(df)
  })

  result_df <- bind_rows(result_list) %>%
    group_by(PulseSpace_s) %>%
    mutate(Light_Level = mean(as.numeric(LightLevel))) %>%
    mutate(Light_Level = round(Light_Level, 3)) %>%
    ungroup()
  
  plot <- result_df %>%
    ggplot()+ 
    geom_path(aes(x= Power.avg, y= Period, col=Power.avg.pval), linewidth=0.8) +
    scale_color_gradient(low="#4AC0AD", high="black", breaks= c(0.05, 1), 
                         labels= c("≤ 0.05", "> 0.05"), guide="legend") +
    labs(x= "Average Wavelet Power", colour= "P-Value") +
    ggh4x::facet_nested(rows=vars(PulseSpace_s, Light_Level), cols = vars(Temp_C)) +
    scale_y_continuous(limits= c(0,10),
                       breaks= c(0,4,8), 
                 sec.axis=sec_axis(~ . , 
                                   name = bquote(Steady ~ State ~ Light ~ (µmol ~ photons ~ m^-2 ~ s^-1)), 
                                   breaks = NULL,labels = NULL)) +
    scale_x_continuous(limits= c(0,1), 
                       breaks=c(0, 0.4, 0.8),
      sec.axis=sec_axis(~ . , name = sym("Measurement Temperature (°C)"), breaks = NULL, labels = NULL)) +
    theme_thesis()
  return(plot)
}
```


```{r Periodicity Test, warning=FALSE}
plot.wt.grid(Ci_wavelets)
plot.wt.grid(Cm_wavelets)
plot.wt.grid(Cr_wavelets)
plot.wt.grid(Cv_wavelets)
plot.wt.grid(Tp_wavelets)
plot.wt.grid(FcG6_wavelets)
plot.wt.grid(FcG0_wavelets)
```


```{r Periodicity Test, warning=FALSE}
plot.wt.grid(Cp_wavelets)
 # ggsave("representative_wtavg.png", width = 9.5, height = 6, dpi = 900,
 #      plot=last_plot(),
 #      path="../Output")
```

# Reconstruction 

```{r}
reconstructions <- readRDS("~/LowLightPhotosynth/Data/ProcessedData/LOW_Reconstructions.Rds") 
reconstruction.list <- split(reconstructions, sub("_.*", "_reconstruction", names(reconstructions)))
list2env(reconstruction.list, envir = .GlobalEnv)

FcG0_reconstruction <- Fc_reconstruction[grepl(paste("_0$", collapse = "|"), names(Fc_reconstruction))]
FcG6_reconstruction <- Fc_reconstruction[grepl(paste("_6$", collapse = "|"), names(Fc_reconstruction))]
```


```{r}
plot.reconstruction <- function(reconstructed) {
  result_list <- Map(function(condition_name, condition_data) {
    series <- as.data.frame(condition_data$series)
    series <- mutate(series, Condition = condition_name) %>%
      mutate(Flashnumber = row_number())  %>%
      separate(Condition, into = c("Strain", "PulseSpace_s", "Temp_C", "LightLevel"),
                sep = "([\\/\\_])") %>%
       mutate(PulseSpace_s = factor(PulseSpace_s, levels = c("1","2","4","8","16")),
             Temp_C = factor(Temp_C, levels = 
                               c("0","2","4","6","8","10","12","14","16","18","20","22","24","26","28")))
    return(series)
  }, names(reconstructed), reconstructed)
  
  result_df <- bind_rows(result_list) %>%
    group_by(PulseSpace_s) %>%
    mutate(Light_Level = mean(as.numeric(LightLevel))) %>%
    mutate(Light_Level = round(Light_Level, 3)) %>%
    ungroup()
  
  plot <- result_df %>%
    ggplot()+
    geom_line(aes(x=Flashnumber, y=FvFmrunnorm, col = "Original")) +
    geom_line(aes(x=Flashnumber, y=FvFmrunnorm.r, col= "Reconstructed"))  +
    scale_colour_manual(values=c("black", "deepskyblue3"), 
                        labels = c("Original", expression(paste("Reconstucted (", alpha, " = 0.05)")))) +
    labs(x= "Flash Number", 
         y=expression("Normalized Chlorophyll Fluorescence (F"[v]*" / F"[m]*")"),
         col= "Wave Function") +
    ggh4x::facet_nested(rows=vars(PulseSpace_s, Light_Level), cols=vars(Temp_C)) +
    scale_y_continuous(sec.axis=sec_axis(~ . , 
                           name = bquote(Steady ~ State ~ Light ~ (µmol ~ photons ~ m^-2 ~ s^-1)), 
                                         breaks = NULL,labels = NULL)) +
    scale_x_continuous(sec.axis=sec_axis(~ . , name = sym("Measurement Temperature (°C)"), 
                                         breaks = NULL, labels = NULL)) +
    theme_thesis()
  
  return(plot)
}
```


```{r warning=FALSE}
plot.reconstruction(Ci_reconstruction)
plot.reconstruction(Cm_reconstruction)
plot.reconstruction(Cr_reconstruction)
plot.reconstruction(Cv_reconstruction)
plot.reconstruction(Tp_reconstruction)
plot.reconstruction(FcG0_reconstruction)
plot.reconstruction(FcG6_reconstruction)
plot.reconstruction(Cp_reconstruction)

 # ggsave("representative_reconstruction.png", width = 10, height = 6, dpi = 900,
 #      plot=last_plot(),
 #      path="../Output")
```


# Damping Across Taxa

```{r}
sstate_damping <- readRDS("~/LowLightPhotosynth/Data/ProcessedData/LOW_SState_Damping.Rds") %>%
  mutate(Strain = factor(Strain))

split.sstate <- split(sstate_damping, sstate_damping$Strain)
names(split.sstate) <- c("Ci_damping", "Cm_damping", "Cp_damping", "Cr_damping", 
                         "Cv_damping", "Fc_damping", "Tp_damping")

list2env(split.sstate, envir = .GlobalEnv)
```



```{r Plot Setup}
strain.labs<- c(
  "Fragilariopsis_cylindrus" = "F. cylindrus",
  "Thalassiosira_pseudonana" = "T. pseudonana",
  "Chlamydomonas_ICEMDV" = "C. ICEMDV",
  "Chlamydomonas_malina" = "C. malina",
  "Chlamydomonas_priscuii" = "C. priscuii",
  "Chlamydomonas_reinhardtii" = "C. reinhardtii",
  "Chlorella_vulgaris" = "C. vulgaris")

temp.labs <- c("0" = "Grown at 0°C",
               "6" = "Grown at 6°C",
               "22" = "Grown at 22°C")

diatom.vlines <- data.frame(
  Strain = c("Fragilariopsis_cylindrus", "Fragilariopsis_cylindrus", "Thalassiosira_pseudonana"),
  GrowthTemp_C = c(0, 6, 22))

algae.vlines <- data.frame(
  Strain = c("Chlamydomonas_ICEMDV", "Chlamydomonas_malina", "Chlamydomonas_priscuii", 
             "Chlorella_vulgaris", "Chlamydomonas_reinhardtii"),
  GrowthTemp_C = c(4.1, 4.1, 4.1, 22, 23.85), 
  ThermalTolerance = c("Polar", "Polar", "Polar", "Temperate", "Temperate"))
```


### Significance Matrix
```{r Plot significance matrix }
mtrx.data <- sstate_damping %>%
  mutate(DampingIndex = ifelse(DampingIndex > 0, 1, 0),
  ThermalTolerance= ifelse(Strain %in% c("Fragilariopsis_cylindrus", 
                           "Chlamydomonas_ICEMDV","Chlamydomonas_priscuii", "Chlamydomonas_malina"),
                           "Polar", 
                           ifelse(Strain %in% c("Chlamydomonas_reinhardtii", "Chlorella_vulgaris",
                                               "Thalassiosira_pseudonana"), "Temperate", NA)), 
  Strain = factor(Strain, levels=c("Fragilariopsis_cylindrus", "Thalassiosira_pseudonana", 
                                   "Chlamydomonas_ICEMDV", "Chlamydomonas_malina", "Chlamydomonas_priscuii",
                                   "Chlorella_vulgaris", "Chlamydomonas_reinhardtii")))
```


```{r Plot significance matrix }
mtrx.data  %>%
  ggplot() +
  geom_tile(aes(x= as.factor(Temp_C), y=as.factor(PulseSpace_s), fill=as.factor(DampingIndex))) +
  scale_fill_manual(values= c("black","skyblue"), 
                      name= bquote(atop("Significance of", "4-Step Periodcity")), 
                      labels =c("p > 0.05", "p ≤ 0.05")) +
  labs(x = "Measurement Temperature (°C)", 
       y= "Flash Spacing (s)") +
  ggh4x::facet_nested_wrap(vars(ThermalTolerance, Strain), ncol=4, nrow=2, scales="free_x", 
                             labeller = labeller(Strain = strain.labs)) +
  theme_thesis() +
  theme(legend.title = element_text(size=11),
        strip.text = element_text(face="italic"),
        legend.position = c(0.97,0.1), legend.justification = c(1,0))

# ggsave("periodicity_mtrx.png", width = 7 , height = 5, dpi = 900,
#        plot=last_plot(),
#        path="../Output")
```


### By Deviation from Growth Temp 
```{r Function for temperature difference }
predict.data.diff <- function(damping) {
  
  Strain <- unique(damping$Strain)
  
  loess <- loess(DampingIndex ~ TempDiff_C * Light_Level, span=0.85, data = damping)
  
  data <- with(damping, expand.grid(
    Light_Level = seq(min(Light_Level), max(Light_Level), 0.1),
    TempDiff_C = seq(min(TempDiff_C), max(TempDiff_C), 0.1)
  ))
  
  predict <- predict(loess, newdata = data)
  
  melt <- reshape2::melt(predict, id.vars = c('TempDiff_C', 'Light_Level'), measure.vars = 'DampingIndex') %>%
    mutate(TempDiff_C = as.numeric(str_sub(TempDiff_C, str_locate(TempDiff_C, '=')[1,1] + 1)),
           Light_Level = as.numeric(str_sub(Light_Level, str_locate(Light_Level, '=')[1,1] + 1))) %>%
    dplyr::rename("DampingIndex" = "value") %>%
    mutate(DampingIndex = ifelse(DampingIndex < 0, 0, DampingIndex)) %>%
    mutate(Strain = Strain, 
           Strain = factor(Strain),
           ThermalTolerance= ifelse(Strain %in% c("Fragilariopsis_cylindrus", 
                           "Chlamydomonas_ICEMDV","Chlamydomonas_priscuii", "Chlamydomonas_malina"),
                           "Polar", 
                           ifelse(Strain %in% c("Chlamydomonas_reinhardtii", "Chlorella_vulgaris",
                                               "Thalassiosira_pseudonana"), "Temperate", NA)),
           ThermalTolerance = factor(ThermalTolerance))
  return(melt)
}
```


```{r predict temperature difference }
predict.diff <- lapply(split.sstate, predict.data.diff)
predict.diff <- bind_rows(predict.diff) 
```


```{r}
#diatoms
diatom.diff <- predict.diff %>%
  filter(Strain %in% c("Fragilariopsis_cylindrus", "Thalassiosira_pseudonana")) %>%
  ggplot(aes(x=TempDiff_C, y=Light_Level, z= DampingIndex)) +
  geom_contour_fill() + 
  geom_contour2(color = "white", linemitre = 10, linewidth=0.25) +
  geom_text_contour(stroke = 0.1, family = "Times New Roman", size = 3.5) +
  labs(x= "Deviation from Growth Temperature (°C)",
       y= expression("Light Level ("*mu*"mol photons m"^"-2"~s^-1*")"),
       fill= "Damping Index") +
  scale_fill_viridis(option="mako", breaks = seq(0, 12, by = 3)) +
  coord_cartesian(ylim = c(0.03, 0.53)) +
  scale_x_continuous(limits= c(-6,6),breaks= c(-12,-8,-4,0,4,8), expand=c(0,0)) +
  scale_y_continuous(breaks= c(0.1,0.2,0.3,0.4,0.5), expand=c(0,0)) +
  ggh4x::facet_nested_wrap(vars(ThermalTolerance, Strain), ncol = 1, strip.position = "right",
                             labeller = labeller(Strain = strain.labs)) +
  theme_thesis() +
  theme(strip.text = element_text(face="italic"))

diatom.diff

# ggsave("diatom_diff.png", width = 6.5 , height = 5, dpi = 900,
#        plot=last_plot(),
#        path="../Output")
```

```{r}
#algae
algae.diff <- predict.diff %>%
  filter(Strain %in% c("Chlamydomonas_ICEMDV", "Chlamydomonas_malina", "Chlamydomonas_priscuii", 
             "Chlorella_vulgaris", "Chlamydomonas_reinhardtii")) %>%
  ggplot(aes(x=TempDiff_C, y=Light_Level, z= DampingIndex)) +
  geom_contour_fill() + 
  geom_contour2(color = "white", linemitre = 10, linewidth=0.25) +
  geom_text_contour(stroke = 0.1, family = "Times New Roman", size = 3.5) +
  labs(x= "Deviation from Growth Temperature (°C)",
       y= expression("Light Level ("*mu*"mol photons m"^"-2"~s^-1*")"),
       fill= "Damping Index") + 
  scale_fill_viridis(option="mako",breaks = seq(0, 12, by = 3)) +
  coord_cartesian(ylim = c(0.03, 0.66)) +
  scale_x_continuous(breaks= c(-12,-8,-4,0,4,8), expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  ggh4x::facet_nested_wrap(vars(ThermalTolerance, Strain), ncol = 1, strip.position = "right",
                           labeller = labeller(Strain=strain.labs)) +
  theme_thesis() +
  theme(strip.text = element_text(face="italic"))

algae.diff

# ggsave("algae_diff.png", width = 7 , height = 8, dpi = 900,
#        plot=last_plot(),
#        path="../Output")
```

To show them together: 
```{r warning=FALSE}
# diff.arrange <- ggarrange(diatom.diff + rremove("ylab") + rremove("xlab"), NA, 
#                     algae.diff + rremove("ylab") + rremove("xlab"),
#                     ncol = 1, heights = c(0.5, 0.05 ,1), 
#                     common.legend = TRUE, legend = "right")
# 
# 
# annotate_figure(diff.arrange, 
#                 left = text_grob(expression("Light Level ("*mu*"mol photons m"^"-2"~s^-1*")"), 
#                                  size= 12, family = "Times", rot = 90, vjust = 1),
#                     bottom = text_grob("Deviation from Growth Temperature (°C)", 
#                                        hjust = 0.75, size= 12, family = "Times"))

# ggsave("sstate_diff.png", width = 11 , height = 7, dpi = 900,
#        plot=last_plot(),
#        path="../Output")
```


### By Measurement Temperature

```{r set function by temp}
predict.data.temp <- function(damping) {
  
  Strain <- unique(damping$Strain)
  GrowthTemp_C <- unique(damping$GrowthTemp_C)
  
  loess <- loess(DampingIndex ~ Temp_C * Light_Level, span=0.8, data = damping)
  
  data <- with(damping, expand.grid(
    Light_Level = seq(min(Light_Level), max(Light_Level), 0.1),
    Temp_C = seq(min(Temp_C), max(Temp_C), 0.1)
  ))
  
  predict <- predict(loess, newdata = data)
  
  melt <- reshape2::melt(predict, id.vars = c('Temp_C', 'Light_Level'), measure.vars = 'DampingIndex') %>%
    mutate(Temp_C = as.numeric(str_sub(Temp_C, str_locate(Temp_C, '=')[1,1] + 1)),
           Light_Level = as.numeric(str_sub(Light_Level, str_locate(Light_Level, '=')[1,1] + 1))) %>%
    dplyr::rename("DampingIndex" = "value") %>%
    mutate(DampingIndex = ifelse(DampingIndex < 0, 0, DampingIndex)) %>%
    mutate(Strain = Strain, GrowthTemp_C = GrowthTemp_C, 
           Strain = factor(Strain),
           ThermalTolerance= ifelse(Strain %in% c("Fragilariopsis_cylindrus", 
                           "Chlamydomonas_ICEMDV","Chlamydomonas_priscuii", "Chlamydomonas_malina"),
                           "Polar", 
                           ifelse(Strain %in% c("Chlamydomonas_reinhardtii", "Chlorella_vulgaris",
                                               "Thalassiosira_pseudonana"), "Temperate", NA)),
           ThermalTolerance = factor(ThermalTolerance))
  return(melt)
}
```


```{r Prepare damping list }
#Split Fc by Growth Temp 
FcG0_damping <- split.sstate[["Fc_damping"]] %>% filter(GrowthTemp_C == 0)
FcG6_damping <- split.sstate[["Fc_damping"]] %>% filter(GrowthTemp_C == 6)

temp.sstate <- list(Ci_damping, Cm_damping, Cp_damping, Cr_damping, Cv_damping, Tp_damping, FcG0_damping, FcG6_damping)
```

```{r by temp df setup}
predict.temp <- lapply(temp.sstate, predict.data.temp)
predict.temp <- bind_rows(predict.temp) 
```


```{r plot diatom temp}
#diatoms
predict.temp %>%
  filter(Strain %in% c("Thalassiosira_pseudonana", "Fragilariopsis_cylindrus")) %>%
  ggplot(aes(x=Temp_C, y=Light_Level, z= DampingIndex)) +
  geom_contour_fill() + 
  geom_contour2(color = "white", linemitre = 10, linewidth=0.25) +
  geom_text_contour(stroke = 0.1, family = "Times New Roman", size = 3.3, 
                    label.placer = label_placer_fraction(frac=0.4)) +
  geom_vline(data=diatom.vlines, aes(xintercept=GrowthTemp_C), col= "white", linetype = "longdash") +
  labs(x= "Measurement Temperature (°C)",
       y= expression("Light Level ("*mu*"mol photons m"^"-2"~s^-1*")"),
       fill= "Damping Index") +
  scale_fill_viridis(option="rocket", breaks = seq(0, 12, by = 3)) +
  coord_cartesian(ylim = c(0.03, 0.53)) +
  scale_x_continuous(breaks = c(2, 6, 10, 14, 18, 22, 26), expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  ggh4x::facet_nested_wrap(vars(Strain, GrowthTemp_C), ncol = 2, 
                           strip.position = "top", scales="free_x", 
                           labeller = labeller(Strain=strain.labs, GrowthTemp_C = temp.labs)) +
  theme_thesis() +
  theme(strip.text = element_text(face="italic"),
        panel.spacing.x = unit(4, "mm"),
        legend.position = c(0.89, 0.07), legend.justification = c(1,0))

# ggsave("diatoms_temp.png", width = 7 , height = 5.5, dpi = 900,
#        plot=last_plot(),
#        path="../Output")
```


```{r plot algae temp}
#algae
predict.temp%>%
  filter(Strain %in% c("Chlamydomonas_ICEMDV", "Chlamydomonas_malina", "Chlamydomonas_priscuii", 
             "Chlorella_vulgaris", "Chlamydomonas_reinhardtii")) %>%
  ggplot(aes(x=Temp_C, y=Light_Level, z= DampingIndex)) +
  geom_contour_fill() + 
  geom_contour2(color = "white", linemitre = 10, linewidth=0.25) +
  geom_text_contour(stroke = 0.1, family = "Times New Roman", size = 3.5, 
                    label.placer = label_placer_random()) +
  labs(x= "Measurement Temperature (°C)",
       y= expression("Light Level ("*mu*"mol photons m"^"-2"~s^-1*")"),
       fill= "Damping Index") +
  geom_vline(data= algae.vlines, aes(xintercept=GrowthTemp_C),
             col= "white", linewidth= 1,  linetype = "dashed") +
  scale_fill_viridis(option="rocket", breaks = seq(0, 12, by = 3)) +
  coord_cartesian(ylim = c(0.05, 0.65)) +
  scale_x_continuous(breaks= c(0,4,8,12,16,20,24,28), expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  ggh4x::facet_nested_wrap(vars(ThermalTolerance, Strain), ncol = 3, strip.position = "top",
                       scales = "free_x", labeller = labeller(Strain = strain.labs)) +
  theme_thesis() +
  theme(strip.text = element_text(face="italic"),
        strip.placement = "outside",
        panel.spacing.x = unit(4, "mm"),
        legend.position = c(0.93, 0.07), legend.justification = c(1,0))

# ggsave("algae_temp.png", width = 9.5 , height = 5.5, dpi = 900,
#        plot=last_plot(),
#        path="../Output")
```

# Other Stuff

```{r}
#GAMs were not the best model for the data 
# library(mgcv)
# Ci <- gam(DampingIndex ~ s(TempDiff_C, k=3) + s(Light_Level), data=Ci.damping)
# Cm <- gam(DampingIndex ~ s(TempDiff_C, k=3) + s(Light_Level), data=Cm.damping)
# Cp <- gam(DampingIndex ~ s(TempDiff_C, k=3) + s(Light_Level), data=Cp.damping)
# Cr <- gam(DampingIndex ~ s(TempDiff_C, k=4) + s(Light_Level), data=Cr.damping)
# Cv <- gam(DampingIndex ~ s(TempDiff_C, k=5) + s(Light_Level), data=Cv.damping)
# Tp <- gam(DampingIndex ~ s(TempDiff_C, k=7) + s(Light_Level), data=Tp.damping)
# Fc <- gam(DampingIndex ~ s(TempDiff_C, k=7) + s(Light_Level), data=Fc.damping)
# 
# vis.gam(Ci, plot.type = "contour")
# vis.gam(Cm, plot.type = "contour")
# vis.gam(Cp, plot.type = "contour")
# vis.gam(Cr, plot.type = "contour")
# vis.gam(Cv, plot.type = "contour")
# vis.gam(Tp, plot.type = "contour")
# vis.gam(Fc, plot.type = "contour")
```
