---
title: "Results (Thesis)"
author: "Natasha Ryan"
output: 
  html_document: default
  word_document: default
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
```


### 3.1 Single Turnover Variable Chlorophyll FLuorescence 

### 3.2 Wavelet Transformations 
```{r}
FcWavelets <- readRDS("../Data/ProcessedData/LOW_FcWavelets.Rds")
CiWavelets <- readRDS("../Data/ProcessedData/LOW_CiWavelets.Rds")
CmWavelets <- readRDS("../Data/ProcessedData/LOW_CmWavelets.Rds")
CpWavelets <- readRDS("../Data/ProcessedData/LOW_CpWavelets.Rds")
CrWavelets <- readRDS("../Data/ProcessedData/LOW_CrWavelets.Rds")
CvWavelets <- readRDS("../Data/ProcessedData/LOW_CvWavelets.Rds")
TpWavelets <- readRDS("../Data/ProcessedData/LOW_TpWavelets.Rds")
```

Example:



### 3.3 Periodicity of Fluorescence Emission

```{r function}
plot.grid.data <- function(wavelets) {
  result_list <- lapply(names(wavelets), function(condition_name) {
    condition <- wavelets[[condition_name]]
    Power.avg <- condition$Power.avg
    Power.avg.pval <- condition$Power.avg.pval
    Period <- condition$Period
    Condition <- rep(condition_name, length(Power.avg))  # Repeat condition name for each row
    df <- data.frame(Power.avg, Power.avg.pval, Period, Condition) %>%
      separate(Condition, into = c("Temp_C", "PulseSpace_s"), sep = "_") 
    
    df$PulseSpace_s <- factor(df$PulseSpace_s, levels = c("1s","2s","4s","8s","16s"))
    
    return(df)
  })

  result_df <- bind_rows(result_list)  # Combine all data frames and add a column for element names
  return(result_df)
}
```


```{r Fc Periodicity Test}
Fc.wt.avg <- plot.grid.data(FcWavelets) %>% 
  mutate(Temp_C = factor(Temp_C, levels = c("10C","6C","2C","0C"))) %>%
  mutate(Power.avg.pval = ifelse(Power.avg.pval <= 0.05, 0, 1))

Fc.wt.avg %>%
  ggplot()+ 
  geom_path(aes(x= Power.avg, y= Period, col=Power.avg.pval), linewidth=0.8) +
  xlim(0, 1) + 
  scale_color_gradient(low="#4AC0AD", high="black", breaks= c(0.05, 1), labels= c("≤ 0.05", "> 0.05"), guide="legend") +
  labs(x= "Average Wavelet Power", colour= "P-Value") +
  facet_grid(rows=vars(Temp_C), cols = vars(PulseSpace_s)) +
  theme_linedraw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r}
Ci.wt.avg <- plot.grid.data(CiWavelets) %>%
  mutate(Temp_C = factor(Temp_C, levels = c("12C","8C","4C"))) %>%
  mutate(Power.avg.pval = ifelse(Power.avg.pval <= 0.05, 0, 1))

Ci.wt.avg %>%
  ggplot()+ 
  geom_path(aes(x= Power.avg, y= Period, col=Power.avg.pval), linewidth=0.8) +
  xlim(0, 1) + 
  scale_color_gradient(low="#4AC0AD", high="black", breaks= c(0.05, 1), labels= c("≤ 0.05", "> 0.05"), guide="legend") +
  labs(x= "Average Wavelet Power", colour= "P-Value") +
  facet_grid(rows=vars(Temp_C), cols = vars(PulseSpace_s)) +
  theme_linedraw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
```

```{r}
Cm.wt.avg <- plot.grid.data(CmWavelets) %>%
  mutate(Temp_C = factor(Temp_C, levels = c("12C","8C","4C"))) %>%
  mutate(Power.avg.pval = ifelse(Power.avg.pval <= 0.05, 0, 1))

Cm.wt.avg %>%
  ggplot()+ 
  geom_path(aes(x= Power.avg, y= Period, col=Power.avg.pval), linewidth=0.8) +
  xlim(0, 1) + 
  scale_color_gradient(low="#4AC0AD", high="black", breaks= c(0.05, 1), labels= c("≤ 0.05", "> 0.05"), guide="legend") +
  labs(x= "Average Wavelet Power", colour= "P-Value") +
  facet_grid(rows=vars(Temp_C), cols = vars(PulseSpace_s)) +
  theme_linedraw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
```

```{r}
Cp.wt.avg <- plot.grid.data(CpWavelets) %>%
  mutate(Temp_C = factor(Temp_C, levels = c("12C","8C","4C"))) %>%
  mutate(Power.avg.pval = ifelse(Power.avg.pval <= 0.05, 0, 1))

Cp.wt.avg %>%
  ggplot()+ 
  geom_path(aes(x= Power.avg, y= Period, col=Power.avg.pval), linewidth=0.8) +
  xlim(0, 1) + 
  scale_color_gradient(low="#4AC0AD", high="black", breaks= c(0.05, 1), labels= c("≤ 0.05", "> 0.05"), guide="legend") +
  labs(x= "Average Wavelet Power", colour= "P-Value") +
  facet_grid(rows=vars(Temp_C), cols = vars(PulseSpace_s)) +
  theme_linedraw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
```

```{r}
Cr.wt.avg <- plot.grid.data(CrWavelets) %>%
  mutate(Temp_C = factor(Temp_C, levels = c("24C","20C","16C", "12C"))) %>%
  mutate(Power.avg.pval = ifelse(Power.avg.pval <= 0.05, 0, 1))

Cr.wt.avg %>%
  ggplot()+ 
  geom_path(aes(x= Power.avg, y= Period, col=Power.avg.pval), linewidth=0.8) +
  xlim(0, 1) + 
  scale_color_gradient(low="#4AC0AD", high="black", breaks= c(0.05, 1), labels= c("≤ 0.05", "> 0.05"), guide="legend") +
  labs(x= "Average Wavelet Power", colour= "P-Value") +
  facet_grid(rows=vars(Temp_C), cols = vars(PulseSpace_s)) +
  theme_linedraw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
```

```{r}
Cv.wt.avg <- plot.grid.data(CvWavelets) %>%
  mutate(Temp_C = factor(Temp_C, levels = c("22C","18C","14C", "10C"))) %>%
  mutate(Power.avg.pval = ifelse(Power.avg.pval <= 0.05, 0, 1))

Cv.wt.avg %>%
  ggplot()+ 
  geom_path(aes(x= Power.avg, y= Period, col=Power.avg.pval), linewidth=0.8) +
  xlim(0, 1) + 
  scale_color_gradient(low="#4AC0AD", high="black", breaks= c(0.05, 1), labels= c("≤ 0.05", "> 0.05"), guide="legend") +
  labs(x= "Average Wavelet Power", colour= "P-Value") +
  facet_grid(rows=vars(Temp_C), cols = vars(PulseSpace_s)) +
  theme_linedraw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
```

```{r}
Tp.wt.avg <- plot.grid.data(TpWavelets) %>%
  mutate(Temp_C = factor(Temp_C, levels = c("22C","18C","14C", "10C"))) %>%
  mutate(Power.avg.pval = ifelse(Power.avg.pval <= 0.05, 0, 1))

Tp.wt.avg %>%
  ggplot()+ 
  geom_path(aes(x= Power.avg, y= Period, col=Power.avg.pval), linewidth=0.8) +
  xlim(0, 1) + 
  scale_color_gradient(low="#4AC0AD", high="black", breaks= c(0.05, 1), labels= c("≤ 0.05", "> 0.05"), guide="legend") +
  labs(x= "Average Wavelet Power", colour= "P-Value") +
  facet_grid(rows=vars(Temp_C), cols = vars(PulseSpace_s)) +
  theme_linedraw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
```

### 3.4 Damping Indices Across Taxa 

```{r}
sstate_damping <- readRDS("~/LowLightPhotosynth/Data/ProcessedData/LOW_SState_Damping.Rds")

sstate_damping$PulseSpace_s <- factor(sstate_damping$PulseSpace_s, levels = c("1","2","4","8","16"))
sstate_damping$Temp_C <- factor(sstate_damping$Temp_C, levels = c("0","2","4","6","8","10","12","14","16","18","20","22","24"))

species.labs <- c("Chlamydomonas ICEMDV", "Chlamydomonas malina", "Chlamydomonas priscuii", "Chlamydomonas reinhardtii", "Chlorella vulgaris", "Fragilariopsis cylindrus", "Thalassiosira pseudonana")
names(species.labs) <- c("Chlamydomonas_ICEMDV", "Chlamydomonas_malina", "Chlamydomonas_priscuii", "Chlamydomonas_reinhardtii", "Chlorella_vulgaris", "Fragilariopsis_cylindrus", "Thalassiosira_pseudonana")

# sstate_damping <- sstate_damping %>%
#   mutate(DampingIndex = ifelse(DampingIndex == 0, NA, DampingIndex))
```


```{r heat map}
sstate_damping %>% 
  ggplot() + 
  geom_tile(aes(x = Temp_C, y = PulseSpace_s, fill = DampingIndex)) +
  viridis::scale_fill_viridis(option="mako", na.value="white") + 
  labs(x= "Temperature (°C)", y= "Flash Spacing (s)", fill= "Damping Index") + 
  facet_wrap(vars(Species), scales = "free", labeller = labeller(Species=species.labs)) +  
  theme_linedraw() +
  theme(strip.text = element_text(face = "italic")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
```




